### ISSUE TITLE
Restrict the columns to the actual queried column set.

### ISSUE THREAD

**Issue by isourabhkr** [exasol/row-level-security#10]
Hi Team,

In the prototype version of the product(RLS), the script finally converts all the select statements(reporting query having the virtual table) to select *, this is a probable bottleneck when we try to scale this solution.

Could you add the functionality to cascade the column set to final pushdown query.

Best,
Sourabh

**Comment by redcatbear** [comment]
Hi @SourabhKr,

seeing that this ticket is from 10 days ago, we are guessing, you did not use the current implementation. The Python demonstrator was discontinued. Please check out the latest version to see if this addresses this ticket.

In the current implementation we list only the original columns the user picked.

Also keep in mind that the current implementation is at an early stage that has the absolute basic functionality. We for example add scripts that make administering RLS-protect more convenient.

Regards,
Sebastian
