### ISSUE TITLE
the script administration-sql-scripts-<>.sql  is not available in the latest RLS release.

### ISSUE THREAD

**Issue by vandanasp** [exasol/row-level-security#122]
the script administration-sql-scripts-<<version>>.sql is not available for the latest release of [Row Level Securtiy latest release.](https://github.com/exasol/row-level-security/releases/tag/3.0.4) but the same is available for the previous releases, [for example here](https://github.com/exasol/row-level-security/releases/tag/3.0.3). We tell the customers in the [installation user guide](https://github.com/exasol/row-level-security/blob/main/doc/user_guide/administration.md#installing-the-administration-scripts), that

> To install the administration scripts, run the SQL batch file administration-sql-scripts-<last-version>.sql. You can find the file on the GitHub release page, the script is released together with the .jar file.

Hence this might create confustion to the customers who want to search for the "administration-sql-scripts" sql script. So request is to add this also to the latest release.

**Comment by kaklakariada** [comment]
Fixed in release [3.0.5](https://github.com/exasol/row-level-security/releases/tag/3.0.5).
