### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by jschildgen** [exasol/row-level-security#27]
https://github.com/exasol/row-level-security 

- "JDBC driver fro Exasol database" => for

https://github.com/exasol/row-level-security/blob/master/doc/user_guide/user_guide.md

- CREATE VIRTUAL SCHEMA => before "SQL_DIALECT" the keyword "WITH" is missing
- CREATE CONNECTION EXASOL_JDBC_CONNECTION TO 'jdbc:exa:&lt;host&gt;:&lt;port&gt;' and EXA_CONNECTION_STRING = '&lt;host&gt;:&lt;port&gt;'; => the host can always be localhost
- I would explain Tenant-based security before Role-based security, because it is simpler

**Comment by AnastasiiaSergienko** [comment]
Closed with #29
