### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by exaValerieWiedemann** [exasol/row-level-security#54]
The link to the deployment guide
https://github.com/exasol/virtual-schemas/blob/master/doc/user-guide/deploying_the_virtual_schema_adapter.md
in the user guide 
https://github.com/exasol/row-level-security/blob/master/doc/user_guide/user_guide.md#installing-the-rls-virtual-schema-package
leads to nirvana.

**Comment by AnastasiiaSergienko** [comment]
Thanks for reporting. The file was renamed meanwhile, we will fix it.
