### ISSUE TITLE
RLS Tutorial: No data for Tenant ZIP_CAB

### ISSUE THREAD

**Issue by exaValerieWiedemann** [exasol/row-level-security#55]
Referring to the tutorial:
https://github.com/exasol/row-level-security/blob/master/doc/user_guide/tutorial.md#creating-the-rls-virtual-schema

When downloading the data from the provided link, there is no data for the provider ZIP_CAB included.
![grafik](https://user-images.githubusercontent.com/35218717/87028443-e6f5f280-c1de-11ea-9734-2003f3f7a1bf.png)
Therefore the virtual schema shows an empty result set when using the user ZIP_CAB

So I'd recommend to either put the download link to a fixed dataset if possible or to change the taxi company in the example to one of the existing ones above

**Comment by redcatbear** [comment]
The problem is that the dataset is steadily appended. If we don't want to download the whole thing, we probably need to add sorting by creation data in combination limiting to the download requests to ensure that the dataset the users use in the demo stays stable.

**Comment by redcatbear** [comment]
Thanks for the hint by the way. I experienced the same thing with a different taxi company earlier, but didn't have an explanation at that time since the problem was solved with a second download. Filter criteria are the key.
