### ISSUE TITLE
Invalid pushdown when combining tenant and group security

### ISSUE THREAD

**Issue by joergbehrmann** [exasol/row-level-security#57]
First of all thank you very much for fulfiling our needs and adding features. We really appreciate that.

- In our use case we tried to combine tenant and group security. 
- Some rows are aligned with user 'RLS_USER1', some with 'RLS_GROUP1' and some with both. 
- RLS_USER1 is not member of any group; RLS_USER2 is a member of RLS_GROUP1. 

When querying the tables with RLS_USER2, which has no assigned lines on tenant level, but is member of RLS_GROUP1 everything works as expected.
But when querying tables with RLS_USER1, which is not member of any group but has assigned rows on tenant level we get an invalid pushdown error.
To avoid invalid pushdowns, we have to assign every user at least one dummy group. Is this the correct way to deal with this issue, or are we missing something?

*of course I changed user and group names to make it easier to understand my point ;)
In this case user RLS_BEHR091 can only query the tables when a dummy group is assigned.

Thanks and best regards,
Jörg

![2020-08-26 16_16_21-Start](https://user-images.githubusercontent.com/58589309/91315073-871bd100-e7b7-11ea-92f9-a69788bd540d.png)

**Comment by redcatbear** [comment]
Hi @joergbehrmann. Without having that checked yet, I am guessing you found a hole in my test harness. Looks like I have to add another test and then fix this.
Thank you very much for reporting this. Feedback is highly appreciated.

**Comment by redcatbear** [comment]
Okay, I reproduced the error in an integration test. The reason (that I did not anticipate) is that the SQL function `IN(...)` is not allowed to be empty. I will add a conditional to fix this.

**Comment by redcatbear** [comment]
@joergbehrmann: Thanks again for reporting. We just released 1.1.2, which resolves the issue.

**Comment by joergbehrmann** [comment]
Oh, nice. Thanks. I'll deploy the new version to our cluster and continue testing tomorrow. :)
