### ISSUE TITLE
Password is exposed in EXPLAIN VIRTUAL for non local EXA connections

### ISSUE THREAD

**Issue by ghost** [exasol/row-level-security#6]
CREATE OR REPLACE CONNECTION EXASOL_CONNECTION 
TO 'jdbc:exa:localhost:8563'
USER 'sys' 
IDENTIFIED BY 'exasol';

CREATE VIRTUAL SCHEMA RLS_VS USING VS_ADAPTER.RLS_ADAPTER WITH
  SQL_DIALECT     = 'RLS'
  CONNECTION_NAME = 'RLS_CONNECTION'
  SCHEMA_NAME     = 'MY_RLS_TESTS'
  ;

CREATE VIRTUAL SCHEMA RLS_VS_2 USING VS_ADAPTER.RLS_ADAPTER WITH
  SQL_DIALECT     = 'RLS'
  CONNECTION_NAME = 'RLS_CONNECTION'
  SCHEMA_NAME     = 'MY_RLS_TESTS'
  IMPORT_FROM_EXA = 'true'
  EXA_CONNECTION_STRING = 'localhost:8563';
  ;

CREATE VIRTUAL SCHEMA RLS_VS_3 USING VS_ADAPTER.RLS_ADAPTER WITH
  SQL_DIALECT     = 'RLS'
  CONNECTION_NAME = 'RLS_CONNECTION'
  SCHEMA_NAME     = 'MY_RLS_TESTS'
  IMPORT_FROM_EXA = 'true'
  EXA_CONNECTION_STRING = 'localhost:8563'
  IS_LOCAL = 'true'
  ;

explain virtual SELECT * FROM rls_vs.TESTTAB2   t;
--> no PW visible

explain virtual SELECT * FROM rls_vs_2.TESTTAB2   t;
--> PW exposed

explain virtual SELECT * FROM rls_vs_2.TESTTAB2   t;
--> no PW visible

**Comment by AnastasiiaSergienko** [comment]
This is a known issue: https://github.com/exasol/virtual-schemas/issues/94
