### ISSUE TITLE
IN list with only one entry

### ISSUE THREAD

**Issue by joergbehrmann** [exasol/row-level-security#60]
Hey everybody,

with the old RLS Python script we had an issue with database users that have only access to one client. The pushdown created an CLIENT IN ('XXX') list with only one entry. In some rare conditions this caused the automated killing of the query because it was using a huge amount of RAM. The workaround, to grant access to an additional non existing dummy client worked to avoid the IN list with only one entry. And the same query that was aborted before, was done in a few seconds.

When using the group based RLS, the same behaviour could appear when a user is assigned to only one group. 
So my question: Would it be best practise to add an additional dummy group to avoid the issue mentioned above?
Since the Exasol isn't that good with single entries in the IN list,  in general.

Thanks and best regards,
Jörg

**Comment by redcatbear** [comment]
Hi @joergbehrmann. I can build in an optimization to turn single IN into a direct predicate "equals".

**Comment by joergbehrmann** [comment]
Hey,
that sounds good.
Thank you!

**Comment by redcatbear** [comment]
On it.

**Comment by redcatbear** [comment]
@joergbehrmann: We just released version 1.2.0 which contains this new feature.
