### ISSUE TITLE
Group based RLS - Admin Scripts - Missing second argument when merging into EXA_GROUP_MEMBERS

### ISSUE THREAD

**Issue by joergbehrmann** [exasol/row-level-security#61]
Hey, 
when adding a user to a group, using the ADD_USER_TO_GROUP script, the MERGE statement is missing a second argument.
Otherwise it is not possible to add a user to an additional group, once he is added to one or more groups.
`MERGE INTO ::s.EXA_GROUP_MEMBERS M
            USING EXA_NEW_GROUP_MEMBERS N
            ON M.EXA_USER_NAME = N.EXA_USER_NAME
            AND M.EXA_GROUP = N.EXA_USER_NAME
            WHEN NOT MATCHED THEN INSERT VALUES (N.EXA_USER_NAME, N.EXA_GROUP)`

Thanks and best regards,
Jörg

**Comment by redcatbear** [comment]
I am guessing there is a typo in the recommended `MERGE`, but I get the point.

> MERGE INTO ::s.EXA_GROUP_MEMBERS M
> USING EXA_NEW_GROUP_MEMBERS N
> ON M.EXA_USER_NAME = N.EXA_USER_NAME AND M.EXA_GROUP = **N.EXA_GROUP**
> WHEN NOT MATCHED
> THEN INSERT VALUES (N.EXA_USER_NAME, N.EXA_GROUP)

**Comment by redcatbear** [comment]
Thanks for reporting this issue, @joergbehrmann.

**Comment by redcatbear** [comment]
@joergbehrmann: We just released version 1.2.0 which contains this fix. Thanks again for reporting.
