### ISSUE TITLE
Add missing dependencies in README

### ISSUE THREAD

**Issue by redcatbear** [exasol/row-level-security#73]
## Situation

When I introduced `project-keeper` (#70 ), I forgot to add the dependencies it introduced into the README.

## Acceptance Criteria

* Missing dependencies are added to README

**Comment by morazow** [comment]
Hey @redcatbear,

What do you think about changing this convention to using the NOTICE file? The project keeper (or one of the included plugins) should already create this file automatically, maybe you need to add the template.

An example: https://github.com/exasol/bucketfs-document-files-virtual-schema/blob/master/NOTICE

**Comment by chiaradiamarcelo** [comment]
@redcatbear this is fixed already in https://github.com/exasol/row-level-security/commit/8ce572c2a24f260fe9f2901a5be91f8323666c7a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by chiaradiamarcelo** [comment]
Reopening, as the one dependency is missing is  `maven-dependency-plugin:3.1.2`
