### ISSUE TITLE
Add own mirror for example data in tutorial

### ISSUE THREAD

**Issue by jakobbraun** [exasol/row-level-security#77]
Sometimes the official source of the example Chicago taxi data is very slow. For that reason, we could set up an S3 bucket with the files.

**Comment by redcatbear** [comment]
While it is true that the original site sometimes is slow, I think the cost-benefit ratio for building a mirror (S3 + CloudFront) is not good enough.

It's not only about recurring infrastructure costs, it's also about setting up, maintaining the mirror and checking the license.

Also if I interpret https://www.kaggle.com/chicago/chicago-taxi-trips-bq right, a mirror on the Google Cloud already exists.
