### ISSUE TITLE
The term "role" is misleading

### ISSUE THREAD

**Issue by exanm** [exasol/row-level-security#82]
The users in RLS are the same as the Exasol database users, but the roles are completely different from the [database roles](https://docs.exasol.com/sql/create_role.htm). Maybe point this out and call them "RLS roles" or use a different term.

Groups could also be confused with [consumer groups](https://docs.exasol.com/sql/consumer_group.htm).

**Comment by redcatbear** [comment]
RLS roles sounds good to me.

**Comment by exanm** [comment]
For consistency I would then recommend calling the groups "RLS groups".
