### ISSUE TITLE
Documentation differs from latest release

### ISSUE THREAD

**Issue by exanm** [exasol/row-level-security#88]
The documentation linked on the [project page](https://github.com/exasol/row-level-security) refers to unreleased features like the LIST_ALL_ROLES script. Maybe link to a tag marking the latest release or don't merge to main until the release?

**Comment by redcatbear** [comment]
This is a situation that we can't fix without a develop branch. Having a develop branch is too much work and also too error prone (we tried it for a long time). If people want the docu for the latest release they need to go via the tag.
