### ISSUE TITLE
Add Constraints for RLS Tables

### ISSUE THREAD

**Issue by exanm** [exasol/row-level-security#92]
I think the administration scripts already prevent invalid data, but it might be a good idea to add PRIMARY KEY and NOT NULL constraints to the RLS tables, e.g. like this:

```sql
CREATE TABLE EXA_ROLES_MAPPING(
    ROLE_NAME VARCHAR(128) CONSTRAINT UNIQUE_ROLE_NAME PRIMARY KEY ENABLE,
    ROLE_ID DECIMAL(2,0) CONSTRAINT VALID_ROLE_ID NOT NULL ENABLE);

CREATE TABLE EXA_RLS_USERS(
    EXA_USER_NAME VARCHAR(128) CONSTRAINT UNIQUE_USER_NAME PRIMARY KEY ENABLE,
    EXA_ROLE_MASK DECIMAL(20,0) CONSTRAINT VALID_ROLE_MASK NOT NULL ENABLE);

CREATE TABLE EXA_GROUP_MEMBERS(
    EXA_USER_NAME VARCHAR(128),
    EXA_GROUP VARCHAR(128),
    CONSTRAINT UNIQUE_GROUP_MEMBERSHIP PRIMARY KEY (EXA_USER_NAME, EXA_GROUP) ENABLE);
```

**Comment by redcatbear** [comment]
I aggree with `EXA_RLS_USERS` and `EXA_GROUP_MEMBERS`, but in the `EXA_ROLES_MAPPING` the ID must be the PK, since this affects the bit mask.
Ideally we would have to separate unique constraints. I wrote a feature ticket for the core.
